//
//  PLVInAppClientErrors.h
//  PaylevenInAppSDK
//
//  Created by ploenne on 18.11.14.
//  Copyright (c) 2014 payleven. All rights reserved.
//

#import <Foundation/Foundation.h>


#define ERROR_INVALID_BACKEND_RESPONSE_CODE 8000
#define ERROR_INVALID_BACKEND_RESPONSE_MESSAGE @"INVALID BACKEND RESPONSE"

#define ERROR_MISSING_API_KEY_CODE 8100
#define ERROR_MISSING_API_KEY_MESSAGE @"MISSING API KEY"

#define ERROR_MISSING_CALLBACK_CODE 8200
#define ERROR_MISSING_CALLBACK_MESSAGE @"MISSING CALLBACK"

#define ERROR_MISSING_EMAILADDRESS_CODE 8300
#define ERROR_MISSING_EMAILADDRESS_MESSAGE @"MISSING EMAILADDRESS"

#define ERROR_MISSING_USERTOKEN_CODE 8400
#define ERROR_MISSING_USERTOKEN_MESSAGE @"MISSING_USERTOKEN"

#define ERROR_MISSING_PAYMENTINSTRUMENTS_CODE 8500
#define ERROR_MISSING_PAYMENTINSTRUMENTS_MESSAGE   @"MISSING PAYMENTINSTRUMENTS"


#define ERROR_CC_EMPTY_CODE 10100
#define ERROR_CC_EMPTY_MESSAGE   @"CREDITCARD NUMBER MISSING"

#define ERROR_CC_INVALID_CODE 10110
#define ERROR_CC_INVALID_MESSAGE   @"CREDITCARD NUMBER INVALID"

#define ERROR_CC_INVALID_CHARS_CODE 10120
#define ERROR_CC_INVALID_CHARS_MESSAGE   @"CREDITCARD NUMBER INVALID CHARACTERS"

#define ERROR_CC_TOO_SHORT_CODE 10130
#define ERROR_CC_TOO_SHORT_MESSAGE   @"CREDITCARD NUMBER TOO SHORT"

#define ERROR_CC_TOO_LONG_CODE 10140
#define ERROR_CC_TOO_LONG_MESSAGE   @"CREDITCARD NUMBER TOO LONG"

#define ERROR_CC_LUM_FAILED_CODE 10150
#define ERROR_CC_LUM_FAILED_MESSAGE   @"CREDITCARD NUMBER INVALID"



#define ERROR_DATE_EMPTY_CODE 10500
#define ERROR_DATE_EMPTY_MESSAGE   @"EXPIRY DATE MISSING"

#define ERROR_DATE_INVALID_CHARS_CODE 10510
#define ERROR_DATE_INVALID_CHARS_MESSAGE   @"EXPIRY DATE INVALID CHARACTERS"

#define ERROR_DATE_MONTH_CODE 10520
#define ERROR_DATE_MONTH_MESSAGE   @"EXPIRY DATE INVALID MONTH"

#define ERROR_DATE_YEAR_CODE 10530
#define ERROR_DATE_YEAR_MESSAGE   @"EXPIRY DATE INVALID YEAR"

#define ERROR_DATE_PASSED_CODE 10540
#define ERROR_DATE_PASSES_MESSAGE   @"EXPIRY DATE PASSED"



#define ERROR_CVV_EMPTY_CODE 10600
#define ERROR_CVV_EMPTY_MESSAGE   @"CVV MISSING"

#define ERROR_CVV_INVALID_CHARS_CODE 10610
#define ERROR_CVV_INVALID_CHARS_MESSAGE   @"CVV INVALID CHARACTERS"

#define ERROR_CVV_TOO_SHORT_CODE 10620
#define ERROR_CVV_TOO_SHORT_MESSAGE   @"CVV INVALID LENGTH"


@interface PLVInAppErrors : NSError

@end
