//
//  PLVInAppClientErrors.h
//  PaylevenInAppSDK
//
//  Created by ploenne on 18.11.14.
//  Copyright (c) 2014 payleven. All rights reserved.
//

#import <Foundation/Foundation.h>


#define ERROR_INVALID_BACKEND_RESPONSE_CODE 8000
#define ERROR_INVALID_BACKEND_RESPONSE_MESSAGE @"INVALID BACKEND RESPONSE"

#define ERROR_MISSING_API_KEY_CODE 8100
#define ERROR_MISSING_API_KEY_MESSAGE @"MISSING API KEY"

#define ERROR_MISSING_CALLBACK_CODE 8200
#define ERROR_MISSING_CALLBACK_MESSAGE @"MISSING CALLBACK"

#define ERROR_MISSING_EMAILADDRESS_CODE 8300
#define ERROR_MISSING_EMAILADDRESS_MESSAGE @"MISSING EMAILADDRESS"

#define ERROR_MISSING_USERTOKEN_CODE 8400
#define ERROR_MISSING_USERTOKEN_MESSAGE @"MISSING_USERTOKEN"

#define ERROR_MISSING_PAYMENTINSTRUMENTS_CODE 8500
#define ERROR_MISSING_PAYMENTINSTRUMENTS_MESSAGE   @"MISSING PAYMENTINSTRUMENTS"


#define ERROR_CC_EMPTY_CODE 10100
#define ERROR_CC_EMPTY_MESSAGE   @"CREDITCARD NUMBER MISSING"

#define ERROR_CC_INVALID_CODE 10110
#define ERROR_CC_INVALID_MESSAGE   @"CREDITCARD NUMBER INVALID"

#define ERROR_CC_INVALID_CHARS_CODE 10120
#define ERROR_CC_INVALID_CHARS_MESSAGE   @"CREDITCARD NUMBER INVALID CHARACTERS"

#define ERROR_CC_TOO_SHORT_CODE 10130
#define ERROR_CC_TOO_SHORT_MESSAGE   @"CREDITCARD NUMBER TOO SHORT"

#define ERROR_CC_TOO_LONG_CODE 10140
#define ERROR_CC_TOO_LONG_MESSAGE   @"CREDITCARD NUMBER TOO LONG"

#define ERROR_CC_LUM_FAILED_CODE 10150
#define ERROR_CC_LUM_FAILED_MESSAGE   @"CREDITCARD NUMBER INVALID"



#define ERROR_SEPA_IBAN_EMPTY_CODE 10200
#define ERROR_SEPA_IBAN_EMPTY_MESSAGE   @"SEPA IBAN NUMBER MISSING"

#define ERROR_SEPA_IBAN_INVALID_LENGTH_CODE 10210
#define ERROR_SEPA_IBAN_INVALID_LENGTH_MESSAGE   @"SEPA IBAN NUMBER INVALID LENGTH"

#define ERROR_SEPA_IBAN_INVALID_CHARS_CODE 10220
#define ERROR_SEPA_IBAN_INVALID_CHARS_MESSAGE   @"SEPA IBAN NUMBER INVALID CHARCATERS"

#define ERROR_SEPA_IBAN_INVALID_CODE 10230
#define ERROR_SEPA_IBAN_INVALID_MESSAGE   @"SEPA IBAN NUMBER INVALID"





#define ERROR_DD_ACCOUNT_MISSING_CODE 10400
#define ERROR_DD_ACCOUNT_MISSING_MESSAGE @"ACCOUNT NUMBER MISSING"

#define ERROR_DD_ACCOUNT_INVALID_CHARS_CODE 10410
#define ERROR_DD_ACCOUNT_INVALID_CHARS_MESSAGE @"ACCOUNT NUMBER INVALID CHARACTERS"

#define ERROR_DD_ACCOUNT_INVALID_LENGTH_CODE 10420
#define ERROR_DD_ACCOUNT_INVALID_LENGTH_MESSAGE @"ACCOUNT NUMBER INVALID LENGTH"



#define ERROR_DD_ROUTING_MISSING_CODE 10450
#define ERROR_DD_ROUTING_MISSING_MESSAGE @"ROUTING NUMBER MISSING"

#define ERROR_DD_ROUTING_INVALID_CHARS_CODE 10460
#define ERROR_DD_ROUTING_INVALID_CHARS_MESSAGE @"ROUTING NUMBER INVALID CHARACTERS"

#define ERROR_DD_ROUTING_INVALID_LENGTH_CODE 10470
#define ERROR_DD_ROUTING_INVALID_LENGTH_MESSAGE @"ROUTING NUMBER INVALID LENGTH"




#define ERROR_PAYPAL_TOKEN_EMPTY_CODE 10300
#define ERROR_PAYPAL_TOKEN_EMPTY_MESSAGE   @"PAYPAL TOKEN MISSING"

#define ERROR_PAYPAL_TOKEN_INVALID_CODE 10310
#define ERROR_PAYPAL_TOKEN_INVALID_MESSAGE   @"PAYPAL TOKEN INVALID"




#define ERROR_DATE_EMPTY_CODE 10500
#define ERROR_DATE_EMPTY_MESSAGE   @"EXPIRY DATE MISSING"

#define ERROR_DATE_INVALID_CHARS_CODE 10510
#define ERROR_DATE_INVALID_CHARS_MESSAGE   @"EXPIRY DATE INVALID CHARACTERS"

#define ERROR_DATE_MONTH_CODE 10520
#define ERROR_DATE_MONTH_MESSAGE   @"EXPIRY DATE INVALID MONTH"

#define ERROR_DATE_YEAR_CODE 10530
#define ERROR_DATE_YEAR_MESSAGE   @"EXPIRY DATE INVALID YEAR"

#define ERROR_DATE_PASSED_CODE 10540
#define ERROR_DATE_PASSES_MESSAGE   @"EXPIRY DATE PASSED"



#define ERROR_CVV_EMPTY_CODE 10600
#define ERROR_CVV_EMPTY_MESSAGE   @"CVV MISSING"

#define ERROR_CVV_INVALID_CHARS_CODE 10610
#define ERROR_CVV_INVALID_CHARS_MESSAGE   @"CVV INVALID CHARACTERS"

#define ERROR_CVV_INVALID_LENGTH_CODE 10620
#define ERROR_CVV_INVALID_LENGTH_MESSAGE   @"CVV INVALID LENGTH"


@interface PLVInAppErrors : NSError

@end
