//
//  PLVInAppErrors.m
//  PaylevenInAppSDK
//
//  Created by ploenne on 18.11.14.
//  Copyright (c) 2014 payleven. All rights reserved.
//

#import "PLVInAppErrors.h"


@implementation PLVInAppClientErrors


NSInteger const ERROR_INVALID_BACKEND_RESPONSE_CODE                 = 8000;

NSString * const ERROR_INVALID_BACKEND_RESPONSE_MESSAGE             = @"INVALID BACKEND RESPONSE";

NSInteger const ERROR_MISSING_API_KEY_CODE                          = 8100;

NSString * const ERROR_MISSING_API_KEY_MESSAGE                      = @"MISSING API KEY";

NSInteger const ERROR_MISSING_CALLBACK_CODE                         = 8200;
NSString * const ERROR_MISSING_CALLBACK_MESSAGE                     = @"MISSING CALLBACK";

NSInteger const ERROR_MISSING_EMAILADDRESS_CODE                     = 8300;
NSString * const ERROR_MISSING_EMAILADDRESS_MESSAGE = @"MISSING EMAILADDRESS";

NSInteger const ERROR_INVALID_EMAILADDRESS_CODE = 8310;
NSString * const ERROR_INVALID_EMAILADDRESS_MESSAGE = @"INVALID EMAILADDRESS";

NSInteger const ERROR_MISSING_USERTOKEN_CODE = 8400;
NSString * const ERROR_MISSING_USERTOKEN_MESSAGE = @"MISSING_USERTOKEN";

NSInteger const ERROR_MISSING_PAYMENTINSTRUMENTS_CODE = 8500;
NSString * const ERROR_MISSING_PAYMENTINSTRUMENTS_MESSAGE  =  @"MISSING PAYMENTINSTRUMENTS";



NSInteger const ERROR_CC_EMPTY_CODE = 10100;
NSString * const ERROR_CC_EMPTY_MESSAGE  =  @"CREDITCARD NUMBER MISSING";

NSInteger const ERROR_CC_INVALID_CODE = 10110;
NSString * const ERROR_CC_INVALID_MESSAGE  =  @"CREDITCARD NUMBER INVALID";

NSInteger const ERROR_CC_INVALID_CHARS_CODE = 10120;
NSString * const ERROR_CC_INVALID_CHARS_MESSAGE  =  @"CREDITCARD NUMBER INVALID CHARACTERS";

NSInteger const ERROR_CC_TOO_SHORT_CODE = 10130;
NSString * const ERROR_CC_TOO_SHORT_MESSAGE  =  @"CREDITCARD NUMBER TOO SHORT";
NSInteger const ERROR_CC_TOO_LONG_CODE = 10140;
NSString * const ERROR_CC_TOO_LONG_MESSAGE  =  @"CREDITCARD NUMBER TOO LONG";

NSInteger const ERROR_CC_LUM_FAILED_CODE = 10150;
NSString * const ERROR_CC_LUM_FAILED_MESSAGE  =  @"CREDITCARD NUMBER INVALID";


NSInteger const ERROR_SEPA_IBAN_EMPTY_CODE = 10200;
NSString * const ERROR_SEPA_IBAN_EMPTY_MESSAGE  =  @"SEPA IBAN MISSING";

NSInteger const ERROR_SEPA_IBAN_INVALID_LENGTH_CODE = 10210;
NSString * const ERROR_SEPA_IBAN_INVALID_LENGTH_MESSAGE  =  @"SEPA IBAN INVALID LENGTH";

NSInteger const ERROR_SEPA_IBAN_INVALID_CHARS_CODE = 10220;
NSString * const ERROR_SEPA_IBAN_INVALID_CHARS_MESSAGE  =  @"SEPA IBAN INVALID CHARCATERS";

NSInteger const ERROR_SEPA_IBAN_INVALID_CODE = 10240;
NSString * const ERROR_SEPA_IBAN_INVALID_MESSAGE  =  @"SEPA IBAN INVALID";


NSInteger const ERROR_SEPA_BIC_EMPTY_CODE = 10260;
NSString * const ERROR_SEPA_BIC_EMPTY_MESSAGE  =  @"SEPA BIC MISSING";

NSInteger const ERROR_SEPA_BIC_INVALID_LENGTH_CODE = 10270;
NSString * const ERROR_SEPA_BIC_INVALID_LENGTH_MESSAGE  =  @"SEPA BIC INVALID LENGTH";

NSInteger const ERROR_SEPA_BIC_INVALID_CHARS_CODE = 10280;
NSString * const ERROR_SEPA_BIC_INVALID_CHARS_MESSAGE  =  @"SEPA BIC INVALID";





NSInteger const ERROR_DD_ACCOUNT_MISSING_CODE = 10400;
NSString * const ERROR_DD_ACCOUNT_MISSING_MESSAGE = @"ACCOUNT NUMBER MISSING";

NSInteger const ERROR_DD_ACCOUNT_INVALID_CHARS_CODE = 10410;
NSString * const ERROR_DD_ACCOUNT_INVALID_CHARS_MESSAGE = @"ACCOUNT NUMBER INVALID CHARACTERS";

NSInteger const ERROR_DD_ACCOUNT_INVALID_LENGTH_CODE = 10420;
NSString * const ERROR_DD_ACCOUNT_INVALID_LENGTH_MESSAGE = @"ACCOUNT NUMBER INVALID LENGTH";


NSInteger const ERROR_DD_ROUTING_MISSING_CODE = 10450;
NSString * const ERROR_DD_ROUTING_MISSING_MESSAGE = @"ROUTING NUMBER MISSING";

NSInteger const ERROR_DD_ROUTING_INVALID_CHARS_CODE = 10460;
NSString * const ERROR_DD_ROUTING_INVALID_CHARS_MESSAGE = @"ROUTING NUMBER INVALID CHARACTERS";

NSInteger const ERROR_DD_ROUTING_INVALID_LENGTH_CODE = 10470;
NSString * const ERROR_DD_ROUTING_INVALID_LENGTH_MESSAGE = @"ROUTING NUMBER INVALID LENGTH";


NSInteger const ERROR_PAYPAL_TOKEN_EMPTY_CODE = 10300;
NSString * const ERROR_PAYPAL_TOKEN_EMPTY_MESSAGE  =  @"PAYPAL TOKEN MISSING";

NSInteger const ERROR_PAYPAL_TOKEN_INVALID_CODE = 10310;
NSString * const ERROR_PAYPAL_TOKEN_INVALID_MESSAGE  =  @"PAYPAL TOKEN INVALID";


NSInteger const ERROR_DATE_EMPTY_CODE = 10500;
NSString * const ERROR_DATE_EMPTY_MESSAGE  =  @"EXPIRY DATE MISSING";

NSInteger const ERROR_DATE_INVALID_CHARS_CODE = 10510;
NSString * const ERROR_DATE_INVALID_CHARS_MESSAGE  =  @"EXPIRY DATE INVALID CHARACTERS";

NSInteger const ERROR_DATE_MONTH_CODE = 10520;
NSString * const ERROR_DATE_MONTH_MESSAGE  =  @"EXPIRY DATE INVALID MONTH";

NSInteger const ERROR_DATE_YEAR_CODE = 10530;
NSString * const ERROR_DATE_YEAR_MESSAGE  =  @"EXPIRY DATE INVALID YEAR";

NSInteger const ERROR_DATE_PASSED_CODE = 10540;
NSString * const ERROR_DATE_PASSES_MESSAGE  =  @"EXPIRY DATE PASSED";



NSInteger const ERROR_CVV_EMPTY_CODE = 10600;
NSString * const ERROR_CVV_EMPTY_MESSAGE  =  @"CVV MISSING";

NSInteger const ERROR_CVV_INVALID_CHARS_CODE = 10610;
NSString * const ERROR_CVV_INVALID_CHARS_MESSAGE  =  @"CVV INVALID CHARACTERS";

NSInteger const ERROR_CVV_INVALID_LENGTH_CODE = 10620;
NSString * const ERROR_CVV_INVALID_LENGTH_MESSAGE  =  @"CVV INVALID LENGTH";



@end
